#!/bin/bash
# Use GitHub Codespace to build rtk_hciattach

echo "🚀 Building rtk_hciattach using GitHub Codespace"
echo "=============================================="
echo ""
echo "Option 1: Use GitHub CLI (if you have a repo):"
echo ""
echo "1. First, create a GitHub repo for this project:"
echo "   gh repo create RV1106-BlueFusion-HFP --public"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git push -u origin main"
echo ""
echo "2. Create and open a codespace:"
echo "   gh codespace create --repo YOUR_USERNAME/RV1106-BlueFusion-HFP"
echo "   gh codespace ssh"
echo ""
echo "3. In the codespace, run:"
echo "   chmod +x build_rtk_hciattach.sh"
echo "   ./build_rtk_hciattach.sh"
echo ""
echo "4. Download the binary:"
echo "   gh codespace cp 'rtk_hciattach/rtk_hciattach' ."
echo ""
echo "Option 2: Use GitHub Actions (already set up):"
echo ""
echo "1. Push to GitHub:"
echo "   git push"
echo ""
echo "2. Go to Actions tab on GitHub"
echo "3. Run the workflow manually"
echo "4. Download the artifact"
echo ""
echo "Option 3: Quick online compile:"
echo ""
echo "Use https://www.onlinegdb.com/online_c_compiler"
echo "1. Select 'C' language"
echo "2. Paste the rtk_hciattach source"
echo "3. Compile for ARM target"
echo ""
echo "Option 4: Use a free Linux VM:"
echo ""
echo "1. https://www.gitpod.io/ (50 hours free/month)"
echo "2. https://replit.com/ (free tier available)"
echo "3. Google Cloud Shell (free)"
echo ""
echo "Once compiled, deploy with:"
echo "adb push rtk_hciattach /tmp/"
echo "adb shell 'chmod +x /tmp/rtk_hciattach'"
echo "adb shell '/tmp/rtk_hciattach -n -s 115200 /dev/ttyS5 rtk_h5'"